name: leya
description: App de alfabeto interativo com letras, sílabas e drawer estilo Duolingo. 

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  flutter_svg: ^2.0.10
  youtube_explode_dart: ^2.2.1
  video_player: ^2.9.1
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: ComicSansMS
      fonts:
        - asset: assets/fonts/ComicSansMS.ttf
    - family: SystemUI
      fonts:
        - asset: assets/fonts/SegoeUI.ttf

  assets:
    - assets/audio/
    - assets/covers/
    - assets/icons/
    - assets/icons/alphabet-icon.png
    - assets/covers/game_memory_cover.png
    - assets/covers/game_quiz_cover.png
    - assets/icons/games-icon.png
    - assets/icons/videos-icon.png
    - assets/icons/menu-icon.svg
    - assets/icons/sun-icon.svg
    - assets/icons/moon-icon.svg
    - assets/icons/music_on.svg
    - assets/icons/music_off.svg
    - assets/icons/chevron-left.svg
    - assets/icons/chevron-right.svg
    - assets/icons/speaker-icon.svg
    - assets/icons/speaker-off-icon.svg
    - assets/icons/back.svg
    - assets/icons/play.svg
    - assets/icons/pause.svg
    - assets/icons/clock.svg
    - assets/icons/forward.svg 
    - assets/icons/rewind.svg
    - assets/icons/easy.png
    - assets/icons/normal.png
    - assets/icons/hard.png
    - assets/icons/extreme.png
#--------------songs---------------
    - assets/songs/playing_song.mp3
    - assets/audio/pressing.wav
    - assets/audio/correct.wav
    - assets/audio/wrong.wav
    - assets/audio/win.wav
    - assets/audio/vowels/
    - assets/audio/consonants/
    - assets/audio/syllables/b/
    - assets/audio/syllables/c/
    #- assets/audio/syllables/d/
    #- assets/audio/syllables/f/
    #- assets/audio/syllables/g/
    #- assets/audio/syllables/h/
    #- assets/audio/syllables/j/
    #- assets/audio/syllables/k/
    #- assets/audio/syllables/l/
    #- assets/audio/syllables/m/
    #- assets/audio/syllables/n/
    #- assets/audio/syllables/p/
    #- assets/audio/syllables/q/
    #- assets/audio/syllables/r/
    #- assets/audio/syllables/s/
    #- assets/audio/syllables/t/
    #- assets/audio/syllables/v/
    #- assets/audio/syllables/w/
    #- assets/audio/syllables/x/
    #- assets/audio/syllables/y/
    #- assets/audio/syllables/z/
#---------------images-----------  
    - assets/images/syllables/b/a/
    - assets/images/syllables/b/e/
    - assets/images/syllables/b/i/
    - assets/images/syllables/b/o/
    - assets/images/syllables/b/u/
    #- assets/images/syllables/c/a/
    #- assets/images/syllables/c/e/
    #- assets/images/syllables/c/i/
    #- assets/images/syllables/c/o/
    #- assets/images/syllables/c/u/
    #- assets/images/syllables/d/a/
    #- assets/images/syllables/d/e/
    #- assets/images/syllables/d/i/
    #- assets/images/syllables/d/o/
    #- assets/images/syllables/d/u/
    #- assets/images/syllables/f/a/
    #- assets/images/syllables/f/e/
    #- assets/images/syllables/f/i/
    #- assets/images/syllables/f/o/
    #- assets/images/syllables/f/u/
    #- assets/images/syllables/g/a/
    #- assets/images/syllables/g/e/
    #- assets/images/syllables/g/i/
    #- assets/images/syllables/g/o/
    #- assets/images/syllables/g/u/
    #- assets/images/syllables/h/a/
    #- assets/images/syllables/h/e/
    #- assets/images/syllables/h/i/
    #- assets/images/syllables/h/o/
    #- assets/images/syllables/h/u/
    #- assets/images/syllables/j/a/
    #- assets/images/syllables/j/e/
    #- assets/images/syllables/j/i/
    #- assets/images/syllables/j/o/
    #- assets/images/syllables/j/u/
    #- assets/images/syllables/k/a/
    #- assets/images/syllables/k/e/
    #- assets/images/syllables/k/i/
    #- assets/images/syllables/k/o/
    #- assets/images/syllables/k/u/
    #- assets/images/syllables/l/a/
    #- assets/images/syllables/l/e/
    #- assets/images/syllables/l/i/
    #- assets/images/syllables/l/o/
    #- assets/images/syllables/l/u/
    #- assets/images/syllables/m/a/
    #- assets/images/syllables/m/e/
    #- assets/images/syllables/m/i/
    #- assets/images/syllables/m/o/
    #- assets/images/syllables/m/u/
    #- assets/images/syllables/n/a/
    #- assets/images/syllables/n/e/
    #- assets/images/syllables/n/i/
    #- assets/images/syllables/n/o/
    #- assets/images/syllables/n/u/
    #- assets/images/syllables/p/a/
    #- assets/images/syllables/p/e/
    #- assets/images/syllables/p/i/
    #- assets/images/syllables/p/o/
    #- assets/images/syllables/p/u/
    #- assets/images/syllables/q/a/
    #- assets/images/syllables/q/e/
    #- assets/images/syllables/q/i/
    #- assets/images/syllables/q/o/
    #- assets/images/syllables/q/u/
    #- assets/images/syllables/r/a/
    #- assets/images/syllables/r/e/
    #- assets/images/syllables/r/i/
    #- assets/images/syllables/r/o/
    #- assets/images/syllables/r/u/
    #- assets/images/syllables/s/a/
    #- assets/images/syllables/s/e/
    #- assets/images/syllables/s/i/
    #- assets/images/syllables/s/o/
    #- assets/images/syllables/s/u/
    #- assets/images/syllables/t/a/
    #- assets/images/syllables/t/e/
    #- assets/images/syllables/t/i/
    #- assets/images/syllables/t/o/
    #- assets/images/syllables/t/u/
    #- assets/images/syllables/v/a/
    #- assets/images/syllables/v/e/
    #- assets/images/syllables/v/i/
    #- assets/images/syllables/v/o/
    #- assets/images/syllables/v/u/
    #- assets/images/syllables/w/a/
    #- assets/images/syllables/w/e/
    #- assets/images/syllables/w/i/
    #- assets/images/syllables/w/o/
    #- assets/images/syllables/w/u/
    #- assets/images/syllables/x/a/
    #- assets/images/syllables/x/e/
    #- assets/images/syllables/x/i/
    #- assets/images/syllables/x/o/
    #- assets/images/syllables/x/u/
    #- assets/images/syllables/y/a/
    #- assets/images/syllables/y/e/
    #- assets/images/syllables/y/i/
    #- assets/images/syllables/y/o/
    #- assets/images/syllables/y/u/
    #- assets/images/syllables/z/a/
    #- assets/images/syllables/z/e/
    #- assets/images/syllables/z/i/
    #- assets/images/syllables/z/o/
    #- assets/images/syllables/z/u/
#----------------videos------------
    - assets/links/videos/playlists/EnsinandoMeuFilho/01_Aprendendo_a_ler/
    - assets/links/videos/playlists/EnsinandoMeuFilho/02_As_Vogais_A_E_I_O_U/
    - assets/links/videos/playlists/EnsinandoMeuFilho/03_Alfabeto/
    - assets/links/videos/playlists/EnsinandoMeuFilho/04_Ensinando_o_alfabeto_para_crianças/
    - assets/links/videos/playlists/EnsinandoMeuFilho/05_Ensinando_as_Sílabas_para_crianças/
    - assets/links/videos/playlists/EnsinandoMeuFilho/06_Silabas_complexas/
    - assets/links/videos/playlists/EnsinandoMeuFilho/07_Formando_palavras/
    - assets/links/videos/playlists/EnsinandoMeuFilho/08_Aprendendo_a_ler_frases_e_textos/
    - assets/links/videos/playlists/EnsinandoMeuFilho/09_Formando_frases_em_inglês/
    - assets/links/videos/playlists/EnsinandoMeuFilho/10_Palavras_cruzadas_-_caça_palavras/
    - assets/links/videos/playlists/EnsinandoMeuFilho/11_Numeros_de_1_a_10/
    - assets/links/videos/playlists/EnsinandoMeuFilho/12_Números/
    - assets/links/videos/playlists/EnsinandoMeuFilho/13_Ensinando_os_números_para_crianças/
    - assets/links/videos/playlists/EnsinandoMeuFilho/14_Tabuada/
    - assets/links/videos/playlists/EnsinandoMeuFilho/15_Divisão_como_aprender_conta_de_dividir/
    - assets/links/videos/playlists/EnsinandoMeuFilho/16_Ensinando_matemática_para_crianças/
    - assets/links/videos/playlists/EnsinandoMeuFilho/17_Educação_financeira/
    - assets/links/videos/playlists/EnsinandoMeuFilho/18_Educação_financeira_para_crianças_e_adolescentes/
    - assets/links/videos/playlists/EnsinandoMeuFilho/19_Inglês_para_crianças/
    - assets/links/videos/playlists/EnsinandoMeuFilho/20_Educação_artistica/
    - assets/links/videos/playlists/EnsinandoMeuFilho/21_Como_a_desenhar_-_Desenhando_passo_a_passo/
    - assets/links/videos/playlists/EnsinandoMeuFilho/22_Dicas_fáceis_de_desenho_para_crianças/
    - assets/links/videos/playlists/EnsinandoMeuFilho/23_Musica_infantil/
    - assets/links/videos/playlists/EnsinandoMeuFilho/24_Ensinando_ciências_para_crianças/
    - assets/links/videos/playlists/EnsinandoMeuFilho/25_De_onde_vem/
    - assets/links/videos/playlists/EnsinandoMeuFilho/26_Ensinando_história_para_crianças/
    - assets/links/videos/playlists/EnsinandoMeuFilho/27_História_do_Brasil/
    - assets/links/videos/playlists/EnsinandoMeuFilho/28_Videos_de_Geografia/
    - assets/links/videos/playlists/EnsinandoMeuFilho/29_Datas_comemorativas_-_Videos_educativos/
    - assets/links/videos/playlists/EnsinandoMeuFilho/30_Libras/