name: leya
description: App de alfabeto interativo com letras, sílabas e drawer estilo Duolingo.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: ComicSansMS
      fonts:
        - asset: assets/fonts/ComicSansMS.ttf
    - family: SystemUI
      fonts:
        - asset: assets/fonts/SegoeUI.ttf

  assets:
    - assets/icons/alphabet-icon.png
    - assets/icons/games-icon.png
    - assets/icons/videos-icon.png
    - assets/audios/vowels/
    - assets/audios/consonants/
    - assets/audios/syllables/b/
    - assets/audios/syllables/c/
    - assets/audios/syllables/d/
    - assets/audios/syllables/f/
    - assets/audios/syllables/g/
    - assets/audios/syllables/h/
    - assets/audios/syllables/j/
    - assets/audios/syllables/k/
    - assets/audios/syllables/l/
    - assets/audios/syllables/m/
    - assets/audios/syllables/n/
    - assets/audios/syllables/p/
    - assets/audios/syllables/q/
    - assets/audios/syllables/r/
    - assets/audios/syllables/s/
    - assets/audios/syllables/t/
    - assets/audios/syllables/v/
    - assets/audios/syllables/w/
    - assets/audios/syllables/x/
    - assets/audios/syllables/y/
    - assets/audios/syllables/z/